# -*- coding: utf-8 -*-
# Copyright (c) Facebook, Inc. and its affiliates.
from detectron2.config import CfgNode as CN


def add_diffusion_config(cfg):
    """
    Add config for MASK_FORMER.
    """
    cfg.MODEL.DIFFUSION = CN()
    cfg.MODEL.DIFFUSION.MODE = 'up'
    cfg.MODEL.DIFFUSION.MODEL_ID = 'model/stable-diffusion-v2'
    cfg.MODEL.DIFFUSION.DATA_TYPE = 'fp32'
    cfg.MODEL.DIFFUSION.HOOK_FLAG = True
    cfg.MODEL.DIFFUSION.CHANNEL_MODIFIC = True
    cfg.MODEL.DIFFUSION.CHANNEL_NUM = 4
    cfg.MODEL.DIFFUSION.SEED = 2024
    cfg.MODEL.DIFFUSION.FLAG_LAYER = 'resnet'
    cfg.MODEL.DIFFUSION.LAYER_INDEXES = [[0, 2], [2, 2], [3, 2]]
    cfg.MODEL.DIFFUSION.TIMESTEP_LIST = [0, ]
    cfg.MODEL.DIFFUSION.GUIDANCE_SCALE = -1
    cfg.MODEL.DIFFUSION.LOW_RESOURCES = True
    cfg.MODEL.DIFFUSION.MULTI_RES_NOISE_FLAG = False
    cfg.MODEL.DIFFUSION.MULTI_RES_NOISE = CN()
    cfg.MODEL.DIFFUSION.MULTI_RES_NOISE.STRENGTH = 0.9
    cfg.MODEL.DIFFUSION.MULTI_RES_NOISE.ANNEALED = True
    cfg.MODEL.DIFFUSION.MULTI_RES_NOISE.DOWNSCALE_STRATEGY = 'original'
    cfg.MODEL.DIFFUSION.NUM_TIMESTEPS = 50
    cfg.MODEL.DIFFUSION.FEATURES_FLAG = False
    cfg.MODEL.DIFFUSION.Q_ADA = True
    cfg.MODEL.DIFFUSION.QUERY_ADA = CN()
    cfg.MODEL.DIFFUSION.QUERY_ADA.NUM_LAYERS = [2, 2, 2, 1, 3, 3, 3]
    cfg.MODEL.DIFFUSION.QUERY_ADA.EMBED_DIMS = [320, 640, 1280, 1280, 1280, 640, 320]
    cfg.MODEL.DIFFUSION.QUERY_ADA.PATCH_SIZES = [8, 16, 32, 64, 32, 16, 8]

    cfg.SOLVER.DIFFUSION_MULTIPLIER = 0.01
